// Code generated by go generate; DO NOT EDIT

package cmds

import "testing"

func rate_limit0(s Builder) {
	s.Gcra().Key("1").MaxBurst(1).TokensPerPeriod(1).Period(1).Count(1).Build()
	s.Gcra().Key("1").MaxBurst(1).TokensPerPeriod(1).Period(1).Build()
}

func TestCommand_InitSlot_rate_limit(t *testing.T) {
	var s = NewBuilder(InitSlot)
	t.Run("0", func(t *testing.T) { rate_limit0(s) })
}

func TestCommand_NoSlot_rate_limit(t *testing.T) {
	var s = NewBuilder(NoSlot)
	t.Run("0", func(t *testing.T) { rate_limit0(s) })
}
